# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N6e0k2Dr9j1K8VygbPWw-HEdLfAdonEp
"""



#task2

def LCS():
  input = open("input2.txt","r")
  output = open("output2.txt","w")
  n = input.readline()
  n = n.strip()
  n = int(n)
  a = input.readline()
  a = a.strip()
  b = input.readline()
  b = b.strip()
  array=[]
  for i in range(len(a)+1):
    array1=[]
    for j in range(len(b)+1):
        array1.append(0)
    array.append(array1)
    
  for i in range(1,len(a)+1):
    for j in range(1,len(b)+1):
      if(a[i-1]==b[j-1]):
        array[i][j]=array[i-1][j-1]+1
            
      else:
        if(array[i-1][j]>array[i][j-1]):
          array[i][j]=array[i-1][j]
        else:
          array[i][j]=array[i][j-1]
                    
  i=len(a)
  j=len(b)
    
  c=""
    
  while(i>0 and j>0):
        
    if(array[i][j]==array[i-1][j]):
      i=i-1
        
    elif(array[i][j]==array[i][j-1]):
      j=j-1
            
    else:
            
      c=c+a[i-1]
            
      i=i-1
      j=j-1
            
  seq = c[::-1]
  keyward = {'Y':'Yasnaya','P':'Pochinki','S':'School','R':'Rozhok','F':'Farm','M':'Mylta','H':'Sheltar','I':'Prison'}

  for elem in seq:
    output.writelines(keyward[elem])
    output.writelines(" ")
  percentage = (len(c)/n)*100
  output.writelines("\n")
  output.writelines("Correctness of prediction: "+str(int(percentage)))
  output.writelines("%")

LCS()