# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QiZcFCiBSkyVOmawUaRGBn3lSqNWlYSZ
"""



#Task-2


f = open("/content/input2_1.txt", "r")
output=open("/content/output2_1.txt","w")
line = f.readline()
a,b = line.split(" ")
b = b.strip()
b = int(b)
a = int(a)
listgraph = [[]]*a
list1 = []
c = 0
while(c<b):
  list2 = []
  line = f.readline()
  d,e = line.split(" ")
  e = e.strip()
  e = int(e)
  d = int(d)
  if d in list1:
    listgraph[d-1].append(e)

  else:
    list1.append(d)
    list2.append(e)
    listgraph[d-1] = list2
  c+=1


graph = listgraph
#print(graph)

visited = [1]
  
Q = [1]
while Q:
  deQ = Q.pop(0)
  output.writelines(str(deQ))
  output.writelines(" ")
  for i in graph[deQ-1]:
    if i not in visited:
      visited.append(i)
      Q.append(i)

