# -*- coding: utf-8 -*-
"""task1A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cylTbStEJF2WcJbbmOUsy-iDcCrkIyAH
"""



#Task1 (i)
input_file=open("/content/input1a_1.txt","r")
output=open("/content/output1a_1.txt","w")
x=input_file.readlines()
list1=[]
for i in range(len(x)):
  y=x[i].strip("\n")
  if i==0:
    n=y.split()
    y=int(n[0])+1
    for j in range(y):
      list1.append([0]*y)
  else:
    value=y.split()
    list1[int(value[0])][int(value[1])]=int(value[2])
for i in range(len(list1)):
  output.writelines(f"{list1[i]}\n")
input_file.close()
output.close()