# -*- coding: utf-8 -*-
"""task1B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JnWtghULVaomgXwpVKsnoYUruiq8AeAw
"""



#Task 1(ii)
input_file=open("/content/input1b_1.txt","r")
output=open("/content/output1b_1.txt","w")
n = input_file.readline()
n,m = n.split()

dic={i:[]for i in range(0,int(n)+1)}
for i in range(int(m)):
    u,v,w=input_file.readline().split()
    dic[int(u)].append((v,w))
for j in dic:
  output.writelines(str(j))
  output.writelines(":")
  output.writelines(str(dic[j]))
  output.writelines("\n")
input_file.close()
output.close()

