# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qmf7N4Ei56OVqtMqxarfitmwCdpLwk_D
"""

#Task- 6


f = open("/content/input6_1", "r")
output=open("/content/output6_1.txt","w")
line = f.readline()
row,clm = line.split(" ")
row = int(row)
clm = int(clm)
list2 = []
for i in range(row):
  list1 = []
  line2 = f.readline()
  for elem in line2:
    list1.append(elem.strip())
  if len(list1)>clm:
    list1.pop()
  list2.append(list1)
print(row,clm)
print(list2)
count = 0
def dfs(r,c,count=0):
  
  if 0>r>row or 0>=c>clm or list2[r-1][c]=='#' or list2[r][c-1]== "#" :
    return count
  else:
    
    if list2[r][c] == "D":
      count+=1
    dfs(r+1,c)
    dfs(r-1,c)
    dfs(r,c+1)
    dfs(r,c-1)
    

dfs(0,2)
output.writelines(str(count))