# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vTPSPL5QEhhqd0GA6yLykRHNHGq0nbAy
"""



#Task-4


f = open("/content/input4_4.txt", "r")

line = f.readline()
a,b = line.split(" ")
b = b.strip()
b = int(b)
a = int(a)
listgraph = [[]]*a
list1 = []
c = 0
while(c<b):
  list2 = []
  line = f.readline()
  d,e = line.split(" ")
  e = e.strip()
  e = int(e)
  d = int(d)
  if d in list1:
    listgraph[d-1].append(e)

  else:
    list1.append(d)
    list2.append(e)
    listgraph[d-1] = list2
  c+=1


graph = listgraph

adj_dict = {}
for i in range(len(graph)):
  adj_dict[i+1] = graph[i]


color = {}
parent = {}
for i in adj_dict.keys():
  color[i] = 'W'
  parent[i] = None



def CycleCheck(vrtx,color,parent):
  #output=open("/content/output4_4.txt","w")
  #flag = False
  color[vrtx] = 'G'
  for i in adj_dict[vrtx]:
    if color[i] == 'W':
      flag = CycleCheck(i,color,parent)
      if flag == True:
        return True
    elif color[i] == 'G':
        return True
  color[vrtx] = 'B'
  return False
output=open("/content/output4_4.txt","w")
flag = False
for vrtx in adj_dict.keys():
  if color[vrtx] == 'W':
    flag = CycleCheck(vrtx,color,parent)
    if flag == True:
      output.writelines("YES")
      break
    else:
      output.writelines("NO")