# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PapXxsdTrDqJdBQXkeK9mtvq7fxTTHWi
"""

#Task-5

def findShortestPath():
  f = open("/content/input5_4.txt", "r")
  output=open("/content/output5_4.txt","w")
  line = f.readline()
  a,b,x = line.split(" ")
  b = b.strip()
  x = x.strip()
  b = int(b)
  a = int(a)
  x = int(x)
  
  listgraph = [[]]*a
  list1 = []
  c = 0
  while(c<b):
    list2 = []
    list3 = []
    line = f.readline()
    d,e = line.split(" ")
    e = e.strip()
    e = int(e)
    d = int(d)
    if d in list1:
      listgraph[d-1].append(e)
    else:
      list1.append(d)
      list2.append(e)
      listgraph[d-1] = list2
    if e in list1:
      listgraph[e-1].append(d)
    else:
      list1.append(e)
      list3.append(d)
      listgraph[e-1] = list3
    c+=1
  #print(listgraph)
  count = 0
  time = {1:0}
  parent = {1:0}
  visited = [1]
  Q = [1]
  while Q:
    deQ = Q.pop(0)
    #if deQ == 1:
      #count =+ 1  
    for i in listgraph[deQ-1]:
      if i not in visited:
        
        visited.append(i)
        Q.append(i)
        parent[i] = deQ
  
  #print("parent",parent)
  visited2 = [1]
  Q = [1]
  while Q:
    deQ = Q.pop(0) 
    count =+ 1
    for i in listgraph[deQ-1]:
      if i not in visited2:
        
        visited2.append(i)
        Q.append(i)
        count = time[parent[i]] + 1
        time[i] = count
  

  output.writelines("Time:")
  output.writelines(" ")
  output.writelines(str(time[x]))
  output.writelines("\n")
  path = []
  i = x
  while i is not 0:
    path.append(i)
    i = parent[i]
  path.reverse()
  output.writelines("Shortest Path:")
  output.writelines(" ")
  for j in path:
    output.writelines(str(j))
    output.writelines(" ")


findShortestPath()