# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gkMh0Q1bFTl-dDgE1XGfPIBHVV4cp4iN
"""

#task4

f1 = open("input4.txt","r")
r1 = f1.readline()
r2 = f1.readline()
r3 = f1.readline()

f2 = open("output4.txt","w")
a = r3.split(" ")
b = r2.split(" ")

for i in range(len(a)):
  a[i]=int(a[i])
  b[i]=int(b[i])

for i in range(len(a)-1):
  for j in range(i+1,0,-1):
    if a[j] > a[j-1]:
      temp = a[j]
      temp2 = b[j]
      a[j] = a[j-1]
      b[j] = b[j-1]
      a[j-1] = temp
      b[j-1] = temp2
    elif a[j] == a[j-1]:
      if b[j] < b[j-1]:
        temp = a[j]
        temp2 = b[j]
        a[j] = a[j-1]
        b[j] = b[j-1]
        a[j-1] = temp
        b[j-1] = temp2

    
for i in range(len(a)):
    f2.writelines("ID: {} Mark: {}\n".format(b[i],a[i]))



f1.close()