# -*- coding: utf-8 -*-
"""task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cWKSJI2Zl9Va-_YJkyTC1BM95Xnnt8PC
"""

#task2

f1 = open("input1b.txt","r")
r1 = f1.readline()
f2 = open("output1b.txt","w")
for line in f1:
  l = line.split(" ")
  a1 = int(l[1])
  a2 = int(l[3])
  
  if l[2]=="+":
    i = (a1+a2)
    f2.writelines("The result of {} {} {} is {}\n".format(a1,l[2],a2,i))
  elif l[2]=="/":
    i = (a1/a2)
    f2.writelines("The result of {} {} {} is {}\n".format(a1,l[2],a2,i))
      
  elif l[2]=="*":
    i = (a1*a2)
    f2.writelines("The result of {} {} {} is {}\n".format(a1,l[2],a2,i))
    
  elif l[2]=="-":
    i = (a1-a2)
    f2.writelines("The result of {} {} {} is {}\n".format(a1,l[2],a2,i))
f1.close()