# -*- coding: utf-8 -*-
"""task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1akbAt6ZVK8e6lJ0Tj4T5zRrYPPIpMPRH
"""

#task 1

f1 = open("input1a.txt","r")
r1 = f1.readline()
f2 = open("output1a.txt","w")

for line in f1:
  line1 = int(line)
  if line1%2 == 0:
    f2.writelines("{} is an Even number. \n".format(line1))
  else:
    f2.writelines("{} is an Odd number.\n".format(line1))

f1.close()