# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/109xvxln8oW-E3ll9jQ70Ma9z_moeGqfE
"""

#task5


f1 = open("input5.txt","r")
r1 = int(f1.readline())
f2 = open("output5.txt","w")
lines = []
lines = [f1.readline().strip() for i in range(1,r1+1)]

for i in range(len(lines)):
  for j in range(0,len(lines)-i-1):
    line1 = lines[j].split(' ')
    line2 = lines[j+1].split(' ')
    if line1[0]>line2[0]:
      lines[j],lines[j+1] = lines[j+1],lines[j]
    elif line1[0] == line2[0] and line1[-1] < line2[-1]:
      lines[j], lines[j+1] = lines[j+1], lines[j]

for i in lines:
  f2.write(i + "\n")

f1.close()