# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UyKlMCK_IAEAn-trVbjqMRyaQ1eXf3sR
"""

from heapq import heapify

def dijkstra(s,d,graph):
  info = {}
  for i in graph:
    info[i] = [10000000,[]]
  info[s][0] = 0
  visited = []
  heap = []
  temp = s
  while temp != d:
    #heap = []
    if temp not in visited:
      visited.append(temp)
    for i in graph[temp]:
      if i not in visited:
        dist = info[temp][0] + graph[temp][i]
        if dist < info[i][0]:
          info[i][0] = dist
          info[i][1] = info[temp][1] + [temp]
        #heappush(heap,(info[i][0],i))
        heap.append((info[i][0],i))
    #heapify(heap)
    #temp = heap[0][1]
    heapify(heap)
    x = heap.pop(0)
    temp = x[1]
  print(info[d][0])
  print(info[d][1]+[d])

graph = graph()
dijkstra("Motijheel","MOGHBAZAR",graph)