# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GDUJaj1cr9SFGsFcu39HoSu1SAneeO0b
"""



#TASK 2

def secdule(arr,person):
  arr2 = []
  arr2.append(arr[0])
  for x in range(1,len(arr)):
    count = 1
    for elem in arr2:
      if arr[x][0] >= elem[1]:
        flag = True

      else:
        flag = False
        count += 1
    if flag == True:
      arr2.append(arr[x])
    elif flag == False and count == person:
      arr2.append(arr[x])
      
  output = open("output2.txt","w")
  output.writelines(str(len(arr2)))

input =open("input2.txt","r")
arr = []
r = input.readline()
n,p = r.split()
for i in range(int(n)):
  m = input.readline()
  x,y = m.split()
  arr.append([int(y),int(x)])
arr.sort()
for i in range(len(arr)):
  arr[i].reverse()

secdule(arr,int(p))