# -*- coding: utf-8 -*-
"""task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fHDQr3WtZR9_mKGoJrd3HYWCSJlsTnQy
"""



#TASK - 3 
input = open("input3.txt","r")
output = open("output3.txt","w")
n = input.readline()
n = int(n)
m = input.readline()
call = input.readline()
arr = []
for elem in m:
  if  elem != " ":
    if elem!='\n':
      elem = int(elem)
      arr.append(elem)
arr.sort()
J = 0 
j = 0 
done_J = [] 
for elem in call:
  if elem == "J":
    hr = arr.pop(0)
    J += hr
    done_J.append(hr)
  if elem == "j":
    hr = done_J.pop()
    j += hr
  
  output.writelines(str(hr))
output.writelines("\n") 
output.writelines("Jack will work for {} hours".format(J))
output.writelines("\n")
output.writelines("Jill will work for {} hours".format(j))