# -*- coding: utf-8 -*-
"""task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9MN1cGUFF0TW-TujFFRHE-U2V08Bqc8
"""



#TASK - 4 (final)
import math

input = open("input4.txt","r")
output = open("output4.txt","w")
x = None
y = None
while x != 0 and y != 0:
  count = 0
  n = input.readline()
  x,y = n.split()
  x = int(x)
  y.strip()
  y = int(y)
  for i in range(x,y+1):
    temp = math.sqrt(i)
    if temp != 0:
      temp2 = math.floor(temp)
      if temp == temp2:
        count+=1
  if count != 0:
    output.writelines(str(count))
    output.writelines("\n")