# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKFixJdfB3IWKJGri_0ZD3IqUGRPfuBV
"""



#TASK 1  

def secdule(arr):
  arr2 = []
  arr2.append(arr[0])
  for x in range(1,len(arr)):
    for elem in arr2:
      if arr[x][0] >= elem[1]:
        flag = True
      else:
        flag = False
        break
    if flag == True:
      arr2.append(arr[x])
  output=open("output1.txt","w")
  output.writelines(str(len(arr2)))
  output.writelines("\n")
  for i in range(len(arr2)):
    output.writelines(str(arr2[i][0]))
    output.writelines(" ")
    output.writelines(str(arr2[i][1]))
    output.writelines("\n")
  

input =open("input1.txt","r")
arr = []
n = input.readline()
for i in range(int(n)):
  m = input.readline()
  x,y = m.split()
  arr.append([int(y),int(x)])
arr.sort()
for i in range(len(arr)):
  arr[i].reverse()

secdule(arr)