# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qQ6ZMlQaAtP39WqCw1Ul6P2PFvkM5Qty
"""



#task 1

def insertionsort(arr1, arr2):
  for i in range(1,len(arr2)):
    temp1 = arr1[i]
    temp2 = arr2[i]
    j = i
    while(j>0 and temp2>arr2[j-1]):
      arr1[j] = arr1[j-1]
      arr2[j] = arr2[j-1]
      j = j-1
    arr1[j] = temp2
    arr1[j] = temp1
  return arr1

f1=open("input1.txt","r")
f2=open("output1.txt","w")
for i in range(2):
    n=(f1.readline())
    array1=f1.readline().split()
    array2=f1.readline().split()
    f2.write(' '.join((insertionsort(array1,array2)))+"\n")

f1.close()
f2.close()